#Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: openkm
  name: openkm
  namespace: alfa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openkm
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: openkm
    spec:
      volumes:
      - name: nfs-vol
        persistentVolumeClaim:
          claimName: nfs-claim
      containers:
      - image: 172.18.0.2/yachay/openkm:6.7.1
        imagePullPolicy: Always
        volumeMounts:
        - name: nfs-vol
          mountPath: /okmRepo
        env:
        - name: JAVA_OPTS
          value: -Dokm.db.jdbc=jdbc:postgresql://172.18.0.30:5432/alfa_openkm -Dokm.db.dirver=org.postgresql.Driver -Dokm.db.user=user_alfa_openkm -Dokm.db.password=SO*Wv#ma
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 30
          httpGet:
            path: /OpenKM
            port: 8080
            scheme: HTTP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          httpGet:
            path: /OpenKM
            port: 8080
            scheme: HTTP
        name: openkm
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 800Mi
      imagePullSecrets:
      - name: yachay-harbor
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openkm
  name: openkm
  namespace: alfa
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort:
    port: 8080
    protocol: TCP
  selector:
    app: openkm
  sessionAffinity: ClientIP
  type: NodePort

---
#Ingress controller

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-hash: md5
    kubernetes.io/ingress.class: nginx
  name: openkm
  namespace: alfa
spec:
  rules:
  - host: alfa-openkm.yachay.gob.ec
    http:
      paths:
      - backend:
          serviceName: openkm
          servicePort: 8080
        path: /
